services:
  - type: web
    name: world-sms
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
    healthCheckPath: "/health"
